# Generated by Django 4.2.7 on 2023-11-10 11:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='계정명')),
                ('email', models.EmailField(max_length=320, unique=True, verbose_name='이메일')),
                ('phone', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='휴대전화 양식을 입력해주세요.', regex='^01([0|1|6|7|8|9]?)-?([0-9]{3,4})-?([0-9]{4})')], verbose_name='휴대전화번호')),
                ('is_active', models.BooleanField(default=False, verbose_name='활성화 여부')),
                ('is_staff', models.BooleanField(default=False, verbose_name='스태프 여부')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='슈퍼유저 여부')),
                ('date_joined', models.DateTimeField(auto_now=True, verbose_name='가입일')),
                ('last_login', models.DateTimeField(auto_now_add=True, verbose_name='마지막 로그인')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
